### ISSUE TITLE
Issues on Mobile 

### ISSUE THREAD

**Issue by ntsieyo** [lagdo/tontine#16]
Quand j'ouvre la page sur mobile, j'ai un problème de rendu. En cliquant sur le bouton de sélection de tontines, le dialogue qui s'ouvre n'est pas responsive sur mobile. J'ai essayé d'ouvrir deux dialogues différents et le résultat est le même.
Voir en image pour l'illustration 
![Screenshot_2023-01-24-14-12-38-58_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/123472865/214305857-d84bafb3-bdc8-485d-80c7-a38187c24128.jpg)

Quand j'active le mode desktop le problème disparaît.
![Screenshot_2023-01-24-14-13-23-25_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/123472865/214306849-12975f7f-2440-4a05-a8f1-5a05f2f9cfca.jpg)

**Comment by feuzeu** [comment]
Hello,

Pour le moment, je déconseille d'utiliser l'application sur mobile.
Elle contient beaucoup de tableaux, et leur affichage sur mobile nécessite un design particulier.
Malheureusement, la priorité est plutôt aux fonctions de gestion des fonds, qui sont au coeur de l'appli.
