### ISSUE TITLE
Missing description on how to contribute

### ISSUE THREAD

**Issue by ntsieyo** [lagdo/tontine#17]
The project is missing the documentation on how to contribute to this project.
Please add a steps required to have an environment ready to develop on contribute to the project.

**Comment by feuzeu** [comment]
Hi,

What do you need to know actually?

The app is made with Laravel, and installed with Composer. Check the readme.
It is quite a common setup with nothing specific.

There are numerous resources online on how to contribute to open source.
You can check this one for example: https://opensource.guide/how-to-contribute/.

It explains many things you can do to contribute, other than writing code.

**Comment by cyrildzumts** [comment]
I'm not a php dev, so let say I want to contribute to UI, I will then work primary on the css/html side, but to test my solutions I will need to run the project on my system. So a step by step guide will be welcomed.
