### ISSUE TITLE
PDF generation problem in the app

### ISSUE THREAD

**Issue by KingT1123** [lagdo/tontine#59]
I realized that there are many functions working on the demo app on internet but not in local while running the project. For example, the problem whille seeding the 'rounds' table beacause in the migration code, there are columns "start_at" and "end_at" thst is not more necessary for this version of your program. 

I will just cite this one.

Nevertheless, there is a problem whle generating the PDF for the reports and transactions entries. There is a mesage saying "**Devtools could not start**". I dont know if it is a dependency to add or any other problem.

**Comment by feuzeu** [comment]
Hello,

La génération de rapport PDF utilise le package https://github.com/chrome-php/chrome.
Effectivement, ce problème a déjà été constaté avec le package, mais malheureusement il n'y a pas eu de solution proposée.
https://github.com/chrome-php/chrome/issues/491

Je suggère de passer à PHP sous Linux avec une solution de virtualisation comme Docker ou VirtualBox.
Il existe des VMs préfaites qui simplifient le déploiement d'une application Laravel.

**Comment by KingT1123** [comment]
D'accord, merci
Mais comme je le demandais, comment se connecter en tant que membre, administrateur ou invite dans l'application en localhost (en tournant le code sur mon pc) ?

**Comment by feuzeu** [comment]
Après avoir installé l'application, et exécuté les migrations, il faut aller sur la page de login, et cliquer sur le bouton Créer un compte. Ou alors exécuter le seeder UserSeeder.php.

**Comment by KingT1123** [comment]
Je suis d'accord.
Mais quand je cree mon compte, comment je saia si je suis Admin, membre ou invite ?
J'aimerais savoir plus sur la logique de fonctionnement de ces entites svp

**Comment by feuzeu** [comment]
Il n'y a pas de compte membre dans cette application.

Chaque compte est administrateur de toutes les tontines qu'il crée, et à donc accès à toutes les fonctionnalités.

Il peut ensuite inviter d'autres utilisateurs, qui ont déjà créé un compte, à gérer également ses tontines, et là il peut définir les fonctions auxquelles les comptes invités ont accès.
